### ISSUE TITLE
Finish Community Currency Website v1

### ISSUE THREAD

**Issue by Kisgus** [CommunityCurrency/Governance#10]
**Remaining edits:**

- [x] Change URL to currency.community
- [x] Change forum url to forum.currency.community
- [x] Create a blog.currency.community based on Ghost / gatsby or similiar open-source tool
- [x] Update Thumbnail
- [x] Update page description
- [x] Make message box work pointing to our emails
- [x] Update below 3x icons with relevant icons to the text from https://www.flaticon.com/

![Screen Shot 2020-07-20 at 7 18 31 PM](https://user-images.githubusercontent.com/18598519/87966646-d6d2f280-cabd-11ea-8826-8fbbad9dea15.png)

- [x] Add embedded youtube link for #Community Currencies NOW channel: https://www.youtube.com/playlist?list=PLy6j39s17_jTEmR81PTV3HfFZqANkYy3-
- [x] Add embedded twitter link displaying latest tweets from: https://twitter.com/CCA_Now
- [x] Add link to Telegram group: https://t.me/joinchat/F8kEMBwROwvwQudzp-Nc0A

**Latest version**

https://communitycurrency.netlify.app/

**Current codebase:**

https://github.com/CommunityCurrency/landing-page

**Comment by seichris** [comment]
FYI i am admin of the ghost blog and can invite anyone to access the site and write blogs :) Just send me your mail!

The frontend of blog.community.currency is hosted at https://github.com/CommunityCurrency/blog. And if you want to change the UI, you have to do it through [shadowing Gatsby components](https://www.gatsbyjs.org/docs/themes/shadowing/).
