### ISSUE TITLE
Executive #6 Community Currencies NOW!

### ISSUE THREAD

**Issue by JuliointheStudio** [CommunityCurrency/Governance#16]
## 📋   Description
make the relevant links and invite the people
## 🎉   Definition of done

- [x] make youtube link
- [x] make group chat and invite the people (Tim Jenkins and Tom)
- [x] promote

## 🤼‍♂️   Reviewer

@

**Comment by Kisgus** [comment]
@Kisgus I'll provide you with social media handle
