### ISSUE TITLE
Setup CCA Praise Bot

### ISSUE THREAD

**Issue by Kisgus** [CommunityCurrency/Governance#6]
**Final text change for CCA customized Praise bot**

🌟 Dear contributor to the Community Currency Alliance 🌟

👏 Congratulations! Your valuable contribution to the CCA has been acknowledged, and you've just received "Praise" which is a personal non-transferable acknowledgment token powered by the Commons Stack. In the future, we are hoping to use a dedicated community currency to spark collaboration between the different projects in the Community Currency Alliance. Please let us know if you have any ideas for the CCA or how you want to get involved 👋

🖥 Join our work at https://currency.community/ 🖥

🌟 Thank you for your support to the Community Currency Alliance 🌟

**Comment by GriffGreen** [comment]
## 📋   Description
We want to update the Commons Stack Praise bot to have a different message for every room! The Praise Testing channel should not give any messages and the CCA channel as well as the CSdDev channel should have their own unique messages.

Right now when you dish praise in the Praise testing room, the bot sends the person the message which means they get the message twice

But we would like for the praise bot to start to conquer telegram, to do this we need to be able to customize the personal DMs per channel that is being dished
## 🎉   What needs to be done

- [x] Write up a short spec of our requirements (in this issue?)
- [x] Write the blurb for each room
- [x] Find the dev to hack it
- [x] Make the PraiseBot an Admin in the CCA channel
- [x] Test it on each other
- [x] Dish praise to all our peeps!


## 🤼‍♂️   Reviewer

@Griff

## 🔗   Links

Here is the config file for the PraiseBot
https://github.com/commons-stack/CommonsStackBot/blob/master/constants.js

**Comment by Kisgus** [comment]
Added updated text description for the description of this issue

**Comment by griff** [comment]
> ## 🤼‍♂️ Reviewer
> @griff

I think you meant @GriffGreen and not me @griff
